OrdererOrgs:
  - Name: Orderer
    Domain: sia.com
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3


PeerOrgs:
  - Name: Org1
    Domain: org1.sia.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.sia.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
 